global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9001']
  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['springlab-kafka-jms:9092']
